language: node_js
node_js:
- stable
deploy:
  provider: npm
  email: 86287344@qq.com
  skip_cleanup: true
  api_key:
    secure: 04X+bzhrkOj/xViyKhJsxc3WGElNk9BYl7wseyylFH2nZ7wiIo3v+tDSJ/s2BkczNY33820AEpWBZFx13A+7P7HXD/ramt44e6i7CZLj+Fpv4Bo2aPwrVqwnB4sCbb4rsl2JOFo3UdVJpj3W/2/i264ew0nLhOPlAl4o3f95Mtuk2teGZvpQGKoaH10IMIRnaNJi3V3on4euYh3vndDem/MiMnwvP/6/osS7uEVw0mxii1Phn+iWnFuKbMDg5zqVbBHz7+i2RnicFi7tTQWcnWLSPOzTEGD3RptkVaT54gGi9Umhu3CUy10khVD0xmKJjH3Di3E9FT2k8h1gTfw1EH9PEqELS/9hNgirw8wptYAPko/64MtJhn7nibVyyBR0q1bV3zegmZHCAU9Hqz8SH40/z6mjjSWu58j9sWvCTBkdQjlIgBkuMLnq6xSqRcqetjnyzIt+IpYo0+XnoIYyrMAZDxBM+Fdl5KN9H1ZLjmGUw1EQoAIdRyKTlgHdGvFvS2SbTJaNwl5YkMDymB4OOeCyvkYmFca6PzzSjBmCTPVd1D7W9COtVFiv3feLd6oC4zThmsr6tq1EO49IJfwVrx43OfmMVWQHGkK6cHekwI//Ow9NU1zuLQktDNkhbfgodxZzpaDrM8AiGqwjDExjzQz8WIaBqQg2JBC6+jdDUAA=
  tag: future
  on:
    branch: vue-component-template
